# Generated by Django 2.2 on 2019-05-29 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=200)),
                ('password1', models.CharField(default='', max_length=200)),
                ('password2', models.CharField(default='', max_length=200)),
                ('dateAccountCreated', models.DateField(default=django.utils.timezone.now)),
                ('foreignkeyToUsers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('textField', models.TextField(max_length=140)),
                ('dateCreated', models.DateField(default=django.utils.timezone.now)),
                ('foreignkeyToUserModel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.UserModel')),
            ],
        ),
    ]
