# Generated by Django 2.2 on 2019-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0003_auto_20190530_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=140)),
            ],
        ),
    ]
