# Generated by Django 2.2 on 2019-06-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0004_messageboardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='foreignkeyToUserModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.UserModel'),
        ),
    ]
