# Generated by Django 2.2 on 2019-06-03 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0005_news_foreignkeytousermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dateCreated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
